#!/bin/bash
rm -rf ./nodes/1
rm -rf ./nodes/2
rm -rf ./nodes/3
rm -rf ./nodes/4
rm -rf ./nodes/5
rm -rf ./nodes/6
rm -rf ./nodes/7
rm -rf ./nodes/8
rm -rf ./nodes/9
rm -rf ./nodes/10
rm -rf ./nodes/11
rm -rf ./nodes/12
rm -rf ./nodes/13
rm -rf ./nodes/14
rm -rf ./nodes/15
rm -rf ./nodes/16
rm -rf ./nodes/17
rm -rf ./nodes/18
rm -rf ./nodes/19
rm -rf ./nodes/20
rm -rf ./nodes/21
rm -rf ./nodes/22
rm -rf ./nodes/23
rm -rf ./nodes/24
